name: FTP → Google Sheets (test every 5m)

on:
  schedule:
    # Test: run every 5 minutes (GitHub minimum interval). Cron is UTC.
    - cron: "*/5 * * * *"
  workflow_dispatch: {}  # manual run for testing

permissions:
  contents: read

concurrency:
  group: ftp-sync
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show runner times (debug)
        run: |
          echo "Runner local time:"
          date
          echo "Runner UTC time:"
          date -u

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Run FTP → Sheets script
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          FTP_DIR:  ${{ secrets.FTP_DIR }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          WORKSHEET_NAME: "OOCL_import"
        run: |
          python -u ftp_to_sheets.py
